name: ProverB to PDF Convertion

on:
  push:
    branches: [ "trigger" ]
  pull_request:
    branches: [ "trigger" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      # Package the jar file
      - name: package
        run: |
          mvn package
          echo Maven package success

      #Upload
      - uses: actions/upload-artifact@v3
        with:
          name: converter
          path: target/ProVerBMate-P2RConverter-1.0.jar

  convert:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download
      - uses: actions/download-artifact@v3
        with:
          name: converter

      # Set Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      # Poll the ProverB
      - name: Pull ProVerB
        run: |
          git clone https://github.com/LiuLiujie/Verification-Tool-Overview.git
          echo Clone ProVerB success

      # Convert
      - name: Convert ProVerB to RDF
        run: |
          chmod 0755 convertor
          java -jar convertor Verification-Tool-Overview/Tools output.xml
          echo Conversion success.