name: ProverB to PDF Convertion

on:
  push:
    branches: [ "trigger" ]
  pull_request:
    branches: [ "trigger" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: package
        run: |
          mvn package
          echo Maven package success

      - name: Pull ProVerB
        run: |
          git clone https://github.com/LiuLiujie/Verification-Tool-Overview.git
          echo Clone ProVerB success
      - name: Convert ProVerB to RDF
        run: |
          echo Conversion success.
